/**
 * Test manifest stub
 * This file is generated by `smrt test`
 *
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import type { SmartObjectManifest } from '@happyvertical/smrt-core/scanner';

export const testManifest: SmartObjectManifest = {
  "version": "1.0.0",
  "timestamp": 1763175784063,
  "objects": {},
  "packageName": "@happyvertical/smrt-svelte"
} as const;

export default testManifest;
